from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from .embeddings import EmbeddingProvider
from .models import Event, Memory


class MemoryStore(Protocol):
    """Narrow domain-facing contract shared by SQLite and PostgreSQL adapters."""

    embedder: EmbeddingProvider

    def transaction(self, *, immediate: bool = False) -> AbstractContextManager[Any]: ...
    def append_event(self, event: Event) -> bool: ...
    def get_event(self, event_id: str) -> Event | None: ...
    def get_memory(self, memory_id: str) -> Memory | None: ...
    def add_memory(self, memory: Memory) -> None: ...
    def active_memories(self, namespace: str) -> list[Memory]: ...
    def purge_memory(self, memory_id: str, reason: str, deleted_at: str) -> None: ...
    def close(self) -> None: ...
